AWSTemplateFormatVersion: 2010-09-09
Parameters:
  AWSAccountId:
    Type: String
  SubnetId:
    Type: 'AWS::EC2::Subnet::Id'
  PrefixName:
    Type: String
Resources:
  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Join ["-", [!Ref PrefixName, "cluster"]]
  EcsSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: !Join ["-", [!Ref PrefixName, "sg"]]
      GroupDescription: Security group for ECS
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 8080
          CidrIp: 0.0.0.0/0
  CloudwatchLogsGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Join 
        - '-'
        - - ECSLogGroup
          - !Ref 'AWS::StackName'
  ECSServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Join ["-", [!Ref PrefixName, "role"]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
  taskdefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: !Join 
        - '-'
        - - !Ref 'AWS::StackName'
          - task
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !Ref ECSServiceRole
      ContainerDefinitions:
        - Name: !Ref PrefixName
          Essential: 'true'
          Image: !Join ["", [!Ref AWSAccountId, ".dkr.ecr.",!Ref 'AWS::Region','.amazonaws.com/',!Ref PrefixName]]
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref CloudwatchLogsGroup
              awslogs-stream-prefix: !Ref PrefixName
          PortMappings:
            - ContainerPort: 8080
      RequiresCompatibilities:
        - EC2
        - FARGATE
  service:
    Type: 'AWS::ECS::Service'
    Properties:
      ServiceName: !Join ["-", [!Ref PrefixName, "service"]] 
      Cluster: !Ref ECSCluster
      DesiredCount: '1'
      TaskDefinition: !Ref taskdefinition
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetId
          SecurityGroups:
            - !GetAtt EcsSecurityGroup.GroupId
Outputs:
  ecsservice:
    Value: !Ref service
  ecscluster:
    Value: !Ref ECSCluster
  taskdef:
    Value: !Ref taskdefinition